# Generated by Django 5.2.1 on 2025-05-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='apple_music_link',
            new_name='applie_music_link',
        ),
    ]
